### ISSUE TITLE
`setGithubStatus` is setting the wrong commit's status when integration is triggered "On Commit"

### ISSUE THREAD

**Issue by pkamb** [drewcrawford/CaveJohnson#6]
My Xcode Bot is triggered to integrate the project on commit.

When it does, `cavejohnson setGithubStatus` is setting the status of the previous commit. 

![screen shot 2015-02-24 at 2 52 29 pm](https://cloud.githubusercontent.com/assets/342355/6361187/d8c9dcfe-bc34-11e4-837d-31c9bdad847c.png)

In the pic above, the integration was triggered by the latest commit. However, the penultimate commit (which was formerly "red") was incorrectly now set again as "green". 

When I select "Integrate Now" via Xcode, the correct commit is annotated.

Still investigating, but is this a known issue? I may have missed a step in Xcode setup.

**Comment by drewcrawford** [comment]
I have seen some odd behavior with github status stuff from time to time, so you're not the only one.

We decide what commit to mark based on parsing an XCS log (since there's not really a better way), and so failure modes could range from, some problem with parsing that log (like if there are multiple entries) to a bug in XCS itself making it output the wrong SHA, etc.

Are you able to consistently reproduce this?  If so then perhaps we can finally shed some light on this dark corner.

**Comment by pkamb** [comment]
Here is a bit of the output of `XCS_OUTPUT_DIR/sourceControl.log` when the integration was triggered by a commit.

`Triggering Commit SHA1` : `0e36ca97f8c29b82076a9e96f1e2a350fe20b63d`
`Previous..   Commit SHA1` : `1834cead9f6912c979495db7ebe1f3e76976cd53`

The method `get_sha()` uses `DVTSourceControlLocationRevisionKey`. In the snippet below, that's getting the previous commit's SHA.

```
2015-02-25 12:02:19.606 XCSCheckoutIntegrationStep.m:339 [XCSCheckoutIntegrationStep saveVersionedBlueprintToIntegration]
[SourceControl] Completed checkout of:
https://pkamb@github.com/apptentive/apptentive-ios.git Branch: C I (@0e36ca97f8c29b82076a9e96f1e2a350fe20b63d) into apptentive-ios-CI 

2015-02-25 12:02:20.083 XCSCheckoutIntegrationStep.m:429 [XCSCheckoutIntegrationStep saveCommitHistory]
[SourceControl] Comparing checked out code with previous blueprint: <XCSBotSCMBlueprint 0x7fa5c599f7c0>
{
  "DVTSourceControlWorkspaceBlueprintLocationsKey" : {
    "DCEE736E74A77829EBFCA9ADD0AF052DBF560B1B" : {
      "DVTSourceControlBranchIdentifierKey" : "CI",
      "DVTSourceControlLocationRevisionKey" : "1834cead9f6912c979495db7ebe1f3e76976cd53",
      "DVTSourceControlBranchOptionsKey" : 50,
      "DVTSourceControlWorkspaceBlueprintLocationTypeKey" : "DVTSourceControlBranch"
    }
  },
  "DVTSourceControlWorkspaceBlueprintPrimaryRemoteRepositoryKey" : "DCEE736E74A77829EBFCA9ADD0AF052DBF560B1B",
  "DVTSourceControlWorkspaceBlueprintIdentifierKey" : "9E2E8A68-75D9-4004-8D31-6831B7DA32CE",
  "DVTSourceControlWorkspaceBlueprintWorkingCopyPathsKey" : {
    "DCEE736E74A77829EBFCA9ADD0AF052DBF560B1B" : "apptentive-ios-CI"
  },
  "DVTSourceControlWorkspaceBlueprintNameKey" : "FeedbackDemo",
  "DVTSourceControlWorkspaceBlueprintVersion" : 203,
  "DVTSourceControlWorkspaceBlueprintRelativePathToProjectKey" : "FeedbackDemo\/FeedbackDemo.xcodeproj",
  "DVTSourceControlWorkspaceBlueprintRemoteRepositoriesKey" : [
    {
      "DVTSourceControlWorkspaceBlueprintRemoteRepositorySystemKey" : "com.apple.dt.Xcode.sourcecontrol.Git",
      "DVTSourceControlWorkspaceBlueprintRemoteRepositoryURLKey" : "https:\/\/github.com\/apptentive\/apptentive-ios.git",
      "DVTSourceControlWorkspaceBlueprintRemoteRepositoryIdentifierKey" : "DCEE736E74A77829EBFCA9ADD0AF052DBF560B1B"
    }
  ]
}

2015-02-25 12:02:20.111 XCSCheckoutIntegrationStep.m:400 [XCSCheckoutIntegrationStep saveCommitHistory]
[SourceControl] Got 1 log items:
Revision: 0e36ca97f8c29b82076a9e96f1e2a350fe20b63d
Author:   Peter Kamb
Date:     2015-02-25 20:01:17 +0000

          Update ATConnect.h

2015-02-25 12:02:20.289 XCSCheckoutIntegrationStep.m:406 [XCSCheckoutIntegrationStep saveCommitHistory]
[SourceControl] Saving commit history, errors: (null)
```

**Comment by drewcrawford** [comment]
So it sounds like you have a reproducible test case of `DVTSourceControlLocationRevisionKey` having an old SHA.  

The question at this point is, whether we can do better.  I see that in your log the string

`Revision: 0e36ca97f8c29b82076a9e96f1e2a350fe20b63d`

contains the right SHA.  Consulting my own logs, however, I see many such lines:

```
[SourceControl] Got 6 log items:
Revision: f75a4f850f605b52a7d6b7a9d86ea9e8d11a8cf1
Author:   Drew Crawford
Date:     2015-02-19 09:32:00 +0000

          [removed]
Revision: 16ec745ed913c0ffb0869915778e64ac21e32af1
Author:   Drew Crawford
Date:     2015-02-19 07:17:24 +0000

          [removed]
Revision: c919b64329b640ce9ce20159d090ee05c70d213d
Author:   Drew Crawford
Date:     2015-02-18 17:30:28 +0000
          
          [removed]
Revision: 4242616f8379c2acb1e7b3d0066797da36a8f54a
Author:   Drew Crawford
Date:     2015-02-14 06:52:15 +0000

          [removed]
Revision: 503b24b48feb65a6f46f3ba843197b4ba19e653a
Author:   Drew Crawford
Date:     2015-02-14 06:47:42 +0000

          [removed]
Revision: ee8cda5784ff5af7818ccbe1f589ff77151c4f1e
Author:   Drew Crawford
Date:     2015-02-14 00:02:57 +0000

          [removed]
```

I think what is happening is this:

1.  The `DVTSourceControlLocationRevisionKey` contains the most recent commit before the server runs `git pull`.  Often this will be the prior commit, or some prior commit, which is why you're seeing old commits.  But in the case that you integrate the same commit twice, it will be the current commit.  That is why this bug has slipped through testing.
2.  The `n log items` lists the commits between the `DVTSourceControlLocationRevisionKey` and the commit being tested.  The topmost item seems newest.

If that is correct then we should be looking for the first log like `Revision: f75a4f850f605b52a7d6b7a9d86ea9e8d11a8cf1` and use that instead of the current behavior.

You're welcome to submit a patch on that topic.  If you don't, I will get to it "eventually".

**Comment by pkamb** [comment]
Yeah, the key is:  

 > [SourceControl] Comparing checked out code with **previous** blueprint: <XCSBotSCMBlueprint 0x7fd3c283ffe0>
